### ISSUE TITLE
unable to compile using clang

### ISSUE THREAD

**Issue by omram89** [thu-pacman/Spindle#1]
Hi,

I'm trying to compile the source code based on the instructions given in the README. At the last step, you've mentioned to compile using: clang -Xclang -load -Xclang mypass.so main.c . This gives me the following error: clang: error: no such file or directory: 'main.c'

I'm not sure what main.c here refers to as there is no file with that name. Could you please help me in resolving this issue.

**Comment by whjthu** [comment]
Hi, 'main.c' is the code you want to analyze by Spindle, so you should provide this code.

**Comment by omram89** [comment]
Thank you for your response. I had another question. When I compile my source code with the same instruction, I'm getting the error: unable to load plugin 'mypass.so'. Is this plugin generated by compiling spindle's source code?

**Comment by whjthu** [comment]
'mypass.so' actually is the Spindle plugin. You should replace this name with the plugin generated by Spindle.
