### ISSUE TITLE
test wrong: undefined symbol

### ISSUE THREAD

**Issue by meton-robean** [thu-pacman/Spindle#2]
## Hi, I ran the test code and got error as following: 
clang -Xclang -load -Xclang ../Spindle/Spindle/libSpindlePass.so -O2 -c testloop.c -o testloop.o
error: unable to load plugin '../Spindle/Spindle/libSpindlePass.so': '../Spindle/Spindle/libSpindlePass.so: undefined symbol:
      _ZN4llvm23EnableABIBreakingChecksE

what's your version of clang?  clang-6.0?

**Comment by whjthu** [comment]
Yes, clang version is 6.0.
Can you provide more information like your system version and LLVM version?

**Comment by meton-robean** [comment]
version: LLVM 6.0.0 ;;    clang-6.0
the system i used is Ubuntu 16.04

**Comment by whjthu** [comment]
I tried the same OS and LLVM version but could not reappear the bug. Usually this bug is raised because clang version is different from LLVM version. Can you run `which clang` to see if you are using clang with the right path?

**Comment by meton-robean** [comment]
it worked! As you said, this bug is raised because clang version is different from LLVM version.  Thanks!
